apiVersion: v1
kind: Service
metadata:
  name: company
  labels:
    app: company
    service: company
spec:
  type: ClusterIP
  selector:
    app: company
  ports:
  - name: rest
    port: 8080
    targetPort: 8080
